# Logical Operators
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(not True)
print(not False)
print(True and True and True)
print(True and True and False)
print(True and False and True)
print(True and False and False)
print(False and True and True)
print(False and True and False)
print(False and False and True)
print(False and False and False)
print(True or True or True)
print(True or True or False)
print(True or False or True)
print(True or False or False)
print(False or True or True)
print(False or True or False)
print(False or False or True)
print(False or False or False)
print(not True and True)
print(not True and False)
print(not False and True)
print(not False and False)
print(not True or True)
print(not True or False)
print(not False or True)
print(not False or False)
print(not True and True and True)
print(not True and True and False)
print(not True and False and True)
print(not True and False and False)
print(not False and True and True)
print(not False and True and False)
print(not False and False and True)
print(not False and False and False)
print(not True or True or True)
print(not True or True or False)
print(not True or False or True)
print(not True or False or False)
print(not False or True or True)
print(not False or True or False)
print(not False or False or True)
print(not False or False or False)
print(not True and not True)
print(not True and not False)
print(not False and not True)
print(not False and not False)
print(3 > 5 and 10 <= 20)
print(True and not True)
print(False or not True and True)
print(True or not True or True)
# Identity Operators
print(5 is 6)
print(5 == 6)
print(5 is not 6)
print(5 != 6)
# Check whether the following code is True or False.
# False or not True and not False
print(False or not True and not False)
# Check whether the following code is True or False.
# True and not False and True or not False
print(True and not False and True or not False)
# Check whether the following code is True or False.
# True or False and False
print(True or False and False)
# Check whether the following code is True or False.
# False and True or False
print(False and True or False)
# Using an identity operator, verify that 10 is not the same as 12.
print(10 is not 12)
# Using an identity operator, verify that 50 is the same as 50.
True or False or False and True